spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parameter_management?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

    # HikariCP ?????
    hikari:
      pool-name: ParameterManagementHikariCP
      minimum-idle: 5                    # ???????
      maximum-pool-size: 20              # ???????
      auto-commit: true                  # ????
      idle-timeout: 30000               # ??????(??)
      max-lifetime: 1800000             # ????????(??)
      connection-timeout: 30000         # ??????(??)
      connection-test-query: SELECT 1   # ??????
      leak-detection-threshold: 60000   # ????????
      connection-init-sql: SET NAMES utf8mb4  # ?????SQL
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
