# src/main/resources/application-prod.yml
spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/parameter_management
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      leak-detection-threshold: 30000
  jpa:
    show-sql: false
